#!/usr/bin/env python

import sys
from optparse import OptionParser

parser = OptionParser(usage="usage: %prog")
(options, args) = parser.parse_args(sys.argv)


import clusto.scripthelpers

config, logger = clusto.scripthelpers.init_script()

from clusto import *

from IPython.Shell import IPShellEmbed
ipshell = IPShellEmbed()
ipshell()
