#!/home/synack/src/clusto/env/bin/python
from clusto.scripthelpers import init_script
import clusto

from os import environ
import sys

def main():
    if len(sys.argv) < 2:
        sys.stderr.write('Usage: %s <server name>\n' % sys.argv[0])
        return -1

    server = clusto.get_by_name(sys.argv[1])
    if not hasattr(server, 'console'):
        sys.stderr.write('%s doesn\'t have a console method\n' % server.name)
        return -1
    server.console(ssh_user=environ.get('CLUSTO_CONSOLE_USER', 'digg'))

if __name__ == '__main__':
    init_script()
    sys.exit(main())
