#!/usr/bin/env python
from clusto.scripthelpers import init_script
from clusto.drivers import IPManager, BasicRack, BasicDatacenter
import clusto

import sys

def get_rack(name):
    try:
        device = IPManager.get_devices(name)
    except:
        device = None

    if not device:
        name = name.split('.', 1)[0]
        try:
            device = clusto.get_by_name(name)
        except:
            return None
    else:
        device = device[0]

    rack = device.parents(clusto_types=[BasicRack])
    if not rack or len(rack) > 1:
        return None
    rack = rack[0]

    datacenter = rack.parents(clusto_types=[BasicDatacenter])
    if not datacenter or len(datacenter) > 1:
        return None
    datacenter = datacenter[0]
    return '/%s/%s' % (datacenter.name, rack.name)

def main():
    if len(sys.argv) < 2:
        sys.stderr.write('Usage: %s <ip>' % sys.argv[0])
        return -1

    try:
        rack = get_rack(sys.argv[1])
        print rack
    except:
        print '/default-rack'
    return 0

if __name__ == '__main__':
    init_script()
    sys.exit(main())
