#!/usr/bin/env python
from clusto.scripthelpers import init_script
from clusto.services import snmp
import sys

def main():
    snmp.log.info('Clusto SNMP server starting')
    init_script()
    for trap in snmp.trap_listen():
        try:
            snmp.update_clusto(trap)
        except:
            snmp.log.error('Exception in run_snmp process')
            snmp.log.error(format_exc())



if __name__ == '__main__':
    sys.exit(main())
