#!/usr/bin/env python
from clusto.scripthelpers import init_script
import clusto
import yaml

import sys

def lookup(name):
    try:
        server = clusto.get_by_name(name)
        return server
    except LookupError:
        try:
            server = clusto.get_by_name(name.split('.', 1)[0])
            return server
        except LookupError:
            return False

def main():
    if len(sys.argv) < 2:
        return -1

    server = lookup(sys.argv[1])
    if not server:
        return -1

    result = {
        'classes': ['site::base-node'],
    }

    disabled = False

    for attr in server.attrs(key='puppet', merge_container_attrs=True):
        if attr.subkey == 'disabled' and attr.value:
            disabled = True

        if attr.subkey == 'class':
            val = str(attr.value)
            if not val in result['classes']:
                result['classes'].append(val)
            continue

        if attr.subkey == 'environment' and not 'environment' in result:
            result['environment'] = str(attr.value)

        if not 'parameters' in result:
            result['parameters'] = {}

        if isinstance(attr.value, int):
            val = attr.value
        else:
            val = str(attr.value)

        subkey = str(attr.subkey)
        if not subkey in result['parameters']:
            result['parameters'][subkey] = val

    if disabled:
        result['classes'] = []
        result['parameters'] = {}

    if not [x for x in result.values() if x]:
        return -1

    yaml.dump(result, sys.stdout, default_flow_style=False, explicit_start=True, indent=2)

if __name__ == '__main__':
    init_script()
    sys.exit(main())
